### ISSUE TITLE
Actually neither the samples

### ISSUE THREAD

**Issue by ccristian** [cpandey05/siessentials#2]
```
/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/bin/java -Didea.launcher.port=7542 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA 15.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/lib/javafx-doclet.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/lib/tools.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/htmlconverter.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Users/cristianchiovari/Work/Projects/siessentials/siexample/target/classes:/Users/cristianchiovari/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar:/Users/cristianchiovari/.m2/repository/org/springframework/integration/spring-integration-test/4.0.1.RELEASE/spring-integration-test-4.0.1.RELEASE.jar:/Users/cristianchiovari/.m2/repository/org/mockito/mockito-core/1.9.5/mockito-core-1.9.5.jar:/Users/cristianchiovari/.m2/repository/org/objenesis/objenesis/1.0/objenesis-1.0.jar:/Users/cristianchiovari/.m2/repository/org/springframework/spring-context/4.0.5.RELEASE/spring-context-4.0.5.RELEASE.jar:/Users/cristianchiovari/.m2/repository/org/hamcrest/hamcrest-all/1.3/hamcrest-all-1.3.jar:/Users/cristianchiovari/.m2/repository/org/springframework/spring-core/4.0.3.RELEASE/spring-core-4.0.3.RELEASE.jar:/Users/cristianchiovari/.m2/repository/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/Users/cristianchiovari/.m2/repository/org/springframework/integration/spring-integration-core/4.0.1.RELEASE/spring-integration-core-4.0.1.RELEASE.jar:/Users/cristianchiovari/.m2/repository/org/springframework/retry/spring-retry/1.1.0.RELEASE/spring-retry-1.1.0.RELEASE.jar:/Users/cristianchiovari/.m2/repository/org/springframework/spring-tx/4.0.5.RELEASE/spring-tx-4.0.5.RELEASE.jar:/Users/cristianchiovari/.m2/repository/org/springframework/spring-messaging/4.0.5.RELEASE/spring-messaging-4.0.5.RELEASE.jar:/Users/cristianchiovari/.m2/repository/org/springframework/spring-aop/4.0.5.RELEASE/spring-aop-4.0.5.RELEASE.jar:/Users/cristianchiovari/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/Users/cristianchiovari/.m2/repository/org/springframework/integration/spring-integration-feed/4.0.1.RELEASE/spring-integration-feed-4.0.1.RELEASE.jar:/Users/cristianchiovari/.m2/repository/net/java/dev/rome/rome-fetcher/1.0.0/rome-fetcher-1.0.0.jar:/Users/cristianchiovari/.m2/repository/jdom/jdom/1.0/jdom-1.0.jar:/Users/cristianchiovari/.m2/repository/xerces/xercesImpl/2.4.0/xercesImpl-2.4.0.jar:/Users/cristianchiovari/.m2/repository/commons-httpclient/commons-httpclient/3.0.1/commons-httpclient-3.0.1.jar:/Users/cristianchiovari/.m2/repository/commons-codec/commons-codec/1.2/commons-codec-1.2.jar:/Users/cristianchiovari/.m2/repository/commons-logging/commons-logging-api/1.0.4/commons-logging-api-1.0.4.jar:/Users/cristianchiovari/.m2/repository/net/java/dev/rome/rome/1.0.0/rome-1.0.0.jar:/Users/cristianchiovari/.m2/repository/org/springframework/integration/spring-integration-mail/4.0.1.RELEASE/spring-integration-mail-4.0.1.RELEASE.jar:/Users/cristianchiovari/.m2/repository/org/springframework/spring-context-support/4.0.5.RELEASE/spring-context-support-4.0.5.RELEASE.jar:/Users/cristianchiovari/.m2/repository/org/springframework/integration/spring-integration-jms/4.0.1.RELEASE/spring-integration-jms-4.0.1.RELEASE.jar:/Users/cristianchiovari/.m2/repository/org/springframework/integration/spring-integration-stream/4.0.1.RELEASE/spring-integration-stream-4.0.1.RELEASE.jar:/Users/cristianchiovari/.m2/repository/org/springframework/integration/spring-integration-jpa/4.0.1.RELEASE/spring-integration-jpa-4.0.1.RELEASE.jar:/Users/cristianchiovari/.m2/repository/org/eclipse/persistence/javax.persistence/2.0.0/javax.persistence-2.0.0.jar:/Users/cristianchiovari/.m2/repository/org/springframework/spring-orm/4.0.5.RELEASE/spring-orm-4.0.5.RELEASE.jar:/Users/cristianchiovari/.m2/repository/org/springframework/integration/spring-integration-file/4.0.1.RELEASE/spring-integration-file-4.0.1.RELEASE.jar:/Users/cristianchiovari/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/Users/cristianchiovari/.m2/repository/org/springframework/integration/spring-integration-ftp/4.0.1.RELEASE/spring-integration-ftp-4.0.1.RELEASE.jar:/Users/cristianchiovari/.m2/repository/commons-net/commons-net/3.3/commons-net-3.3.jar:/Users/cristianchiovari/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar:/Users/cristianchiovari/.m2/repository/javax/activation/activation/1.1.1/activation-1.1.1.jar:/Users/cristianchiovari/.m2/repository/javax/mail/mail/1.4.5/mail-1.4.5.jar:/Users/cristianchiovari/.m2/repository/org/apache/velocity/velocity/1.7/velocity-1.7.jar:/Users/cristianchiovari/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar:/Users/cristianchiovari/.m2/repository/org/apache/activemq/activemq-core/5.7.0/activemq-core-5.7.0.jar:/Users/cristianchiovari/.m2/repository/org/slf4j/slf4j-api/1.6.6/slf4j-api-1.6.6.jar:/Users/cristianchiovari/.m2/repository/org/apache/geronimo/specs/geronimo-jms_1.1_spec/1.1.1/geronimo-jms_1.1_spec-1.1.1.jar:/Users/cristianchiovari/.m2/repository/org/apache/activemq/kahadb/5.7.0/kahadb-5.7.0.jar:/Users/cristianchiovari/.m2/repository/org/apache/activemq/protobuf/activemq-protobuf/1.1/activemq-protobuf-1.1.jar:/Users/cristianchiovari/.m2/repository/org/fusesource/mqtt-client/mqtt-client/1.3/mqtt-client-1.3.jar:/Users/cristianchiovari/.m2/repository/org/fusesource/hawtdispatch/hawtdispatch-transport/1.11/hawtdispatch-transport-1.11.jar:/Users/cristianchiovari/.m2/repository/org/fusesource/hawtdispatch/hawtdispatch/1.11/hawtdispatch-1.11.jar:/Users/cristianchiovari/.m2/repository/org/fusesource/hawtbuf/hawtbuf/1.9/hawtbuf-1.9.jar:/Users/cristianchiovari/.m2/repository/org/apache/geronimo/specs/geronimo-j2ee-management_1.1_spec/1.0.1/geronimo-j2ee-management_1.1_spec-1.0.1.jar:/Users/cristianchiovari/.m2/repository/org/jasypt/jasypt/1.9.0/jasypt-1.9.0.jar:/Users/cristianchiovari/.m2/repository/org/springframework/spring-jms/4.0.3.RELEASE/spring-jms-4.0.3.RELEASE.jar:/Users/cristianchiovari/.m2/repository/org/springframework/spring-beans/4.0.3.RELEASE/spring-beans-4.0.3.RELEASE.jar:/Users/cristianchiovari/.m2/repository/com/h2database/h2/1.3.168/h2-1.3.168.jar:/Users/cristianchiovari/.m2/repository/org/hibernate/hibernate-entitymanager/4.0.1.Final/hibernate-entitymanager-4.0.1.Final.jar:/Users/cristianchiovari/.m2/repository/org/jboss/spec/javax/transaction/jboss-transaction-api_1.1_spec/1.0.0.Final/jboss-transaction-api_1.1_spec-1.0.0.Final.jar:/Users/cristianchiovari/.m2/repository/dom4j/dom4j/1.6.1/dom4j-1.6.1.jar:/Users/cristianchiovari/.m2/repository/xml-apis/xml-apis/1.0.b2/xml-apis-1.0.b2.jar:/Users/cristianchiovari/.m2/repository/org/hibernate/hibernate-core/4.0.1.Final/hibernate-core-4.0.1.Final.jar:/Users/cristianchiovari/.m2/repository/antlr/antlr/2.7.7/antlr-2.7.7.jar:/Users/cristianchiovari/.m2/repository/org/hibernate/javax/persistence/hibernate-jpa-2.0-api/1.0.1.Final/hibernate-jpa-2.0-api-1.0.1.Final.jar:/Users/cristianchiovari/.m2/repository/org/jboss/logging/jboss-logging/3.1.0.CR2/jboss-logging-3.1.0.CR2.jar:/Users/cristianchiovari/.m2/repository/org/javassist/javassist/3.15.0-GA/javassist-3.15.0-GA.jar:/Users/cristianchiovari/.m2/repository/org/hibernate/common/hibernate-commons-annotations/4.0.1.Final/hibernate-commons-annotations-4.0.1.Final.jar:/Users/cristianchiovari/.m2/repository/org/springframework/integration/spring-integration-jdbc/4.0.1.RELEASE/spring-integration-jdbc-4.0.1.RELEASE.jar:/Users/cristianchiovari/.m2/repository/org/springframework/spring-jdbc/4.0.5.RELEASE/spring-jdbc-4.0.5.RELEASE.jar:/Users/cristianchiovari/.m2/repository/com/google/guava/guava/16.0.1/guava-16.0.1.jar:/Users/cristianchiovari/.m2/repository/org/springframework/integration/spring-integration-twitter/4.0.1.RELEASE/spring-integration-twitter-4.0.1.RELEASE.jar:/Users/cristianchiovari/.m2/repository/org/springframework/social/spring-social-twitter/1.1.0.RELEASE/spring-social-twitter-1.1.0.RELEASE.jar:/Users/cristianchiovari/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.3.2/jackson-annotations-2.3.2.jar:/Users/cristianchiovari/.m2/repository/org/springframework/security/spring-security-crypto/3.2.3.RELEASE/spring-security-crypto-3.2.3.RELEASE.jar:/Users/cristianchiovari/.m2/repository/org/springframework/social/spring-social-config/1.1.0.RELEASE/spring-social-config-1.1.0.RELEASE.jar:/Users/cristianchiovari/.m2/repository/org/springframework/social/spring-social-web/1.1.0.RELEASE/spring-social-web-1.1.0.RELEASE.jar:/Users/cristianchiovari/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/Users/cristianchiovari/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.3.2/jackson-core-2.3.2.jar:/Users/cristianchiovari/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.3.2/jackson-databind-2.3.2.jar:/Users/cristianchiovari/.m2/repository/org/springframework/social/spring-social-core/1.1.0.RELEASE/spring-social-core-1.1.0.RELEASE.jar:/Users/cristianchiovari/.m2/repository/org/springframework/spring-web/4.0.5.RELEASE/spring-web-4.0.5.RELEASE.jar:/Users/cristianchiovari/.m2/repository/org/springframework/integration/spring-integration-xml/4.0.1.RELEASE/spring-integration-xml-4.0.1.RELEASE.jar:/Users/cristianchiovari/.m2/repository/org/springframework/spring-oxm/4.0.5.RELEASE/spring-oxm-4.0.5.RELEASE.jar:/Users/cristianchiovari/.m2/repository/org/springframework/ws/spring-xml/2.2.0.RELEASE/spring-xml-2.2.0.RELEASE.jar:/Users/cristianchiovari/.m2/repository/org/springframework/integration/spring-integration-ws/4.0.1.RELEASE/spring-integration-ws-4.0.1.RELEASE.jar:/Users/cristianchiovari/.m2/repository/org/springframework/spring-webmvc/4.0.5.RELEASE/spring-webmvc-4.0.5.RELEASE.jar:/Users/cristianchiovari/.m2/repository/org/springframework/ws/spring-ws-core/2.2.0.RELEASE/spring-ws-core-2.2.0.RELEASE.jar:/Users/cristianchiovari/.m2/repository/org/springframework/spring-expression/4.0.5.RELEASE/spring-expression-4.0.5.RELEASE.jar:/Users/cristianchiovari/.m2/repository/org/springframework/batch/spring-batch-core/3.0.1.RELEASE/spring-batch-core-3.0.1.RELEASE.jar:/Users/cristianchiovari/.m2/repository/com/ibm/jbatch/com.ibm.jbatch-tck-spi/1.0/com.ibm.jbatch-tck-spi-1.0.jar:/Users/cristianchiovari/.m2/repository/javax/batch/javax.batch-api/1.0/javax.batch-api-1.0.jar:/Users/cristianchiovari/.m2/repository/com/thoughtworks/xstream/xstream/1.4.7/xstream-1.4.7.jar:/Users/cristianchiovari/.m2/repository/xmlpull/xmlpull/1.1.3.1/xmlpull-1.1.3.1.jar:/Users/cristianchiovari/.m2/repository/xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.jar:/Users/cristianchiovari/.m2/repository/org/codehaus/jettison/jettison/1.2/jettison-1.2.jar:/Users/cristianchiovari/.m2/repository/org/springframework/batch/spring-batch-infrastructure/3.0.1.RELEASE/spring-batch-infrastructure-3.0.1.RELEASE.jar:/Users/cristianchiovari/.m2/repository/postgresql/postgresql/9.0-801.jdbc4/postgresql-9.0-801.jdbc4.jar:/Users/cristianchiovari/.m2/repository/commons-dbcp/commons-dbcp/1.4/commons-dbcp-1.4.jar:/Users/cristianchiovari/.m2/repository/commons-pool/commons-pool/1.5.4/commons-pool-1.5.4.jar:/Users/cristianchiovari/.m2/repository/org/springframework/batch/spring-batch-integration/3.0.1.RELEASE/spring-batch-integration-3.0.1.RELEASE.jar:/Applications/IntelliJ IDEA 15.app/Contents/lib/idea_rt.jar" com.intellij.rt.execution.application.AppMain com.cpandey.siexample.Aggregator
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'soJavaFeedAdapterForAggregator.source': Unsatisfied dependency expressed through constructor argument with index 0 of type [java.net.URL]: Could not convert constructor argument value of type [java.lang.String] to required type [java.net.URL]: Failed to convert value of type 'java.lang.String' to required type 'java.net.URL'; nested exception is java.lang.IllegalArgumentException: Could not retrieve URL for class path resource [urltofetchfeedfrom]: class path resource [urltofetchfeedfrom] cannot be resolved to URL because it does not exist
Related cause: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'soJavaFeedAdapterForAggregator.source': Unsatisfied dependency expressed through constructor argument with index 0 of type [java.net.URL]: Could not convert constructor argument value of type [java.lang.String] to required type [java.net.URL]: Failed to convert value of type 'java.lang.String' to required type 'java.net.URL'; nested exception is java.lang.IllegalArgumentException: Could not retrieve URL for class path resource [urltofetchfeedfrom]: class path resource [urltofetchfeedfrom] cannot be resolved to URL because it does not exist
    at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:722)
    at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:185)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1114)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1017)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:703)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:760)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
    at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
    at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
    at com.cpandey.siexample.Aggregator.main(Aggregator.java:21)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Related cause:

```

**Comment by cpandey05** [comment]
Thanks for bringing this to notice. Seems Spring is not picking the test config files by "Convention" - I have added code to explicitly look for config files on class path (Something like @ContextConfiguration(locations = {"classpath:*/TestSplitter-context.xml"})). This now seems to be working. Please try and let me know. Before you start using the examples, please build the project using Maven target "mvn -X clean package" so that it can get all of these dependencies
